
 const INGESTION_FLOW=[
    {
        id:1,
        name:"Title",
        apiFieldName:"title",
        description:"This should contain the title of content",
        mandatory:"YES",
    },
    {
        id:2,
        name:"Description",
        apiFieldName:"description",
        description:"This should contain the synopsis of given content",
        mandatory:"YES",
    },
    {
        id:3,
        name:"Short Description",
        apiFieldName:"short_description",
        description:"A brief description about content in less than 150 characters",
        mandatory:"NO",
    },
    {
        id:4,
        name:"Title",
        apiFieldName:"title",
        description:"This should contain the title of content",
        mandatory:"YES",
    },
    {
        id:5,
        name:"Portrait Image of Aspect Ratio 2:3",
        apiFieldName:"portrait_23",
        description:"Portrait image to be displayed for a content",
        mandatory:"YES",
    },
    {
        id:6,
        name:"Landscape Image of Aspect Ratio 16:9",
        apiFieldName:"landscape_169",
        description:"Landscape image to be displayed for a content",
        mandatory:"YES",
    },
    {
        id:7,
        name:"Unique content identifier",
        apiFieldName:"contentId",
        description:"A unique ID to identify the contents. This will be used to uniquely identify a content between Airtel and the partner in case of issues.",
        mandatory:"YES",
    },
    {
        id:8,
        name:"Credits",
        apiFieldName:"credits",
        description:"List of actors, directors, producers etc",
        mandatory:"NO",
    },
    {
        id:9,
        name:"Duration",
        apiFieldName:"duration",
        description:"Duration of content (In seconds preferably)",
        mandatory:"YES",
    },
    {id:10,
        name:"Release Date/Year",
        apiFieldName:"releaseDate",
        description:"Release date or year of the content",
        mandatory:"YES",
    },
    {id:11,
        name:"Expiry Date of Content",
        apiFieldName:"expiryTime",
        description:"The timestamp after which content will be removed/expired",
        mandatory:"NO",
    },
    {id:12,
        name:"Free/Paid flag",
        apiFieldName:"isFree",
        description:"Boolean value representing if content is free or paid",
        mandatory:"YES",
    },
    {id:13,
        name:"Genres",
        apiFieldName:"geners",
        description:"Genres list of the conten",
        mandatory:"YES",
    },
    {id:14,
        name:"Downloadable Flag",
        apiFieldName:"isDownloadable",
        description:"Boolean value representing if content is downloadable or not",
        mandatory:"YES",
    },
    {id:15,
        name:"Age Rating*",
        apiFieldName:"ageRating",
        description:"Age Rating of content as per OTT guidelines",
        mandatory:"YES",
    },
    {id:16,
        name:"Content Type**",
        apiFieldName:"contentType",
        description:"To identify the content type",
        mandatory:"YES",
    },
    {id:17,
        name:"Stream Urls",
        apiFieldName:"streamUrls",
        description:"List of HLS/DASH stream urls of content (Refer to point 5 for more details)",
        mandatory:"NO",
    },
    {id:18,
        name:"Language",
        apiFieldName:"language",
        description:"List of audio languages used in content",
        mandatory:"YES",
    },
    {id:19,
        name:"Feature Banner HD",
        apiFieldName:"featureBannerHD",
        description:"Feature banner for displaying on Large screens. Dimension : 2280x699 / 300ppi",
        mandatory:"YES",
    },
    
        
]


export default INGESTION_FLOW;