const MOVIES_TABLE=[
    {id:1,
        name:"Duration",
        apiFieldName:"duration",
        description:"Duration of trailer",
        mandatory:"YES",
    },
    {id:2,
        name:"Title",
        apiFieldName:"title",
        description:"Title of trailer. If not provide MOVIE_NAME - TRAILER will be used",
        mandatory:"NO",
    },
    {id:3,
        name:"Trailer URL",
        apiFieldName:"trailerUrl",
        description:"HLS/DASH URL of trailer video",
        mandatory:"YES",
    },
    {id:4,
        name:"Portrait Image of Aspect Ratio 2:3",
        apiFieldName:"portrait_23",
        description:"Portrait image to be displayed for trailer",
        mandatory:"YES",
    },
    {id:5,
        name:"Landscape Image of Aspect Ratio 16:9",
        apiFieldName:"landscape_169",
        description:"Landscape image to be displayed for trailer",
        mandatory:"YES",
    },

]

export default MOVIES_TABLE;